### ISSUE TITLE
Choose subdomain to host on demos.haus

### ISSUE THREAD

**Issue by steverydz** [canonical-web-and-design/tools.demos.haus#12]

**Comment by steverydz** [comment]
I think a good name for this would be tools.demo.haus as @pmahnke suggested in standup.

@nottrobin @jpmartinspt do you know how I can get this project on that domain?

**Comment by jpmartinspt** [comment]
@steverydz There is an RT open with IS to point all subdomains of `demos.haus` at our demo cluster. If we want `demo.haus` instead we can configure it in our digital ocean account.

**Comment by steverydz** [comment]
@jpmartinspt sorry, I meant "demos" rather than "demo"
