### ISSUE TITLE
Illustration isn't rendered to images in Firefox

### ISSUE THREAD

**Issue by steverydz** [canonical-web-and-design/tools.demos.haus#22]
In Firefox the illustration isn't rendered to any of the images. This is because without width and height attributes on the root `svg` element the browser interprets the dimensions as 0 x 0.

There are a number of bugs filed about this on bugzilla:
- https://bugzilla.mozilla.org/show_bug.cgi?id=700533
- https://bugzilla.mozilla.org/show_bug.cgi?id=1283234

![Screenshot from 2020-07-10 15-17-58](https://user-images.githubusercontent.com/501889/87164538-c9995500-c2c0-11ea-81e0-e16ddbae4b7f.png)

**Comment by steverydz** [comment]
@hatched bug filed as requested

**Comment by anasereijo** [comment]
@steverydz is this still happening?

**Comment by steverydz** [comment]
@anasereijo yes, but there is nothing we can do until Firefox fix their bug, which they seem to be in no hurry to do

**Comment by anasereijo** [comment]
> @anasereijo yes, but there is nothing we can do until Firefox fix their bug, which they seem to be in no hurry to do

I see. So if there's nothing we can do, can we close this then?

**Comment by steverydz** [comment]
I guess so. There's nothing we can do on our side. If they fix it then it should just work.
