### ISSUE TITLE
Add download links for each social image

### ISSUE THREAD

**Issue by steverydz** [canonical-web-and-design/tools.demos.haus#8]
Each social image should have a download link underneath

**Comment by steverydz** [comment]
@nottrobin @jpmartinspt are we able to open up the cors permissions for assets.ubuntu.com?

Because the canvas for each banner contains images from assets.ubuntu.com I'm not able to convert the canvas to a dataURL (for downloading purposes) unless cors allows it for the embedded images.

**Comment by nottrobin** [comment]
We can't make changes to assets until we move it to k8s, but also, it's difficult to see how this could be supported in assets.ubuntu.com in general. We'd need to look quite deeply into the security implications of "opening up cors permissions".

The faster solution would be that any images you needed cross-site access to were hosted elsewhere, or you found a way to grab the necessary images from assets.ubuntu.com server-side.

**Comment by steverydz** [comment]
Thanks @nottrobin.

It's most likely that the images will come from assets as that's where our illustrations are hosted, although technically the user can put any URL for the illustration they want to use, so opening up assets would only partially solve the issue.

The problem with fetching the image server side is that it would have to be hosted within the app, which means we would be hosting a second assets server of sorts.

I don't see a way around this so I think the only thing we can do is prompt the user to right click/save image.

**Comment by nottrobin** [comment]
> The problem with fetching the image server side is that it would have to be hosted within the app, which means we would be hosting a second assets server of sorts.

Not necessarily - we could instead proxy live through the backend app. As in, `tools.demos.haus/getmemyimage?url=https://assets.ubuntu.com/v1/something.jpg`.
